### ISSUE TITLE
Link 'Command Line API' in README leads to 404

### ISSUE THREAD

**Issue by hliyan** [nodejs/node-inspect#104]
The link [Command Line API](https://developers.google.com/web/tools/chrome-devtools/debug/command-line/command-line-reference?hl=en) in README.md leads to a non-existed document.

**Comment by jkrems** [comment]
Thanks for letting us know!

We're about to archive this repo since the code officially moved into node core. I'm not sure if it's worth fixing the link at this point.

**Comment by Trott** [comment]
I couldn't find a reasonable current version so I deleted it. If anyone knows where those docs went, we can add it back.
