### ISSUE TITLE
CI setup for node-inspect

### ISSUE THREAD

**Issue by joshgav** [nodejs/node-inspect#21]
Travis and Appveyor configurations are specified in the repo, but the Node.js projects don't generally support integration with Travis (see e.g. https://github.com/nodejs/github-bot/issues/57).

So we can either set up this repo to be tested by Node's own Jenkins CI, or perhaps make arrangements to use Travis like [citgm](https://github.com/nodejs/citgm).

CI work is in progress for node-report too in https://github.com/nodejs/node-report/issues/18 and https://github.com/nodejs/build/issues/610. @mhdawson based on your work there can you suggest the right approach for node-inspect?

**Comment by mhdawson** [comment]
To get coverage across our platforms it really needs to be the Node.js Jenkins CI.

If we are in agreement I can open the issue to get the ok to setup jobs based on: https://github.com/nodejs/build/blob/master/doc/process/jenkins_job_configuation_access.md

That would let us setup a "node-inspect" team who's members could start the jobs and "node-inspect-admin" team who could edit the jobs.  

If its simply a matter of a job that install the module and then runs the tests I can then one up based on what was done for node-report.

**Comment by jkrems** [comment]
`npm install` / `npm test` with build status would definitely be great.

On travis I had also a setup for automated PR labels & releases from CI (potentially using a shared/headless user). Not sure if anything like that exists for some node core project..? Otherwise I can do the releases manually from my machine using my own github/npm credentials.

**Comment by mhdawson** [comment]
In terms of release I think we'd also like something like that in the Node.js CI.  We need the same thing for node-report and I've go the action to see how we can setup a common "nodejs" identity that we can use for publishing the modules.  

Maybe we can re-use your automated setup, I think @sam-github had mentioned that there are some strongloop tools/scripts for publishing modules we should look at.

**Comment by mhdawson** [comment]
I assume that testing node-inspect should be associated with the diagnostics wg.

**Comment by mhdawson** [comment]
Create https://github.com/nodejs/build/issues/625 to start process as documented for getting CI jobs for a workgroup.

**Comment by mhdawson** [comment]
initial CI runs here https://ci.nodejs.org/view/x%20-%20Diagnostics/job/node-inspect-continuous-integration/

**Comment by rnchamberlain** [comment]
@mhdawson Oi! I am getting (lots of) email reports from these node-inspect CI builds. I guess the config was copied from node-report, including my email address. The email address is in the "Post-build Actions" panel right at the bottom of the config, but I don't have powers on node-inspect to fix it.

Incidently, we've made a few changes recently to the node-report CI config, including switching from using citgm to just direct 'npm test' - which improves the console output a lot. Might be worth copying that.

**Comment by jkrems** [comment]
@mhdawson Did you have time to look into the notification settings and/or simplifying the setup to use `npm test` directly? Or would you prefer to track this in a separate issue?

**Comment by jkrems** [comment]
The repo now uses a Github workflow for testing.
