### ISSUE TITLE
Auto reconnect on restart (using with nodemon)

### ISSUE THREAD

**Issue by lukerohde** [nodejs/node-inspect#27]
I work from the terminal so finding this made my day.  Thanks.  

I can't find any info on auto reconnecting when using node restarts.  I'm using nodemon which restarts on every save.  I can break and manually reconnect but this may get old.   I'd be great if it could realise when the connection was lost and reconnect.  Possible?

**Comment by jkrems** [comment]
That definitely sounds possible and useful in other situations as well (e.g. remote debugging where the connection could drop temporarily). I assume a simple "Connection lost. Press any key to reconnect." would be enough?

**Comment by lukerohde** [comment]
The chrome extension NIM has a configurable polling interval of 3 seconds, but this feels a bit laggy.  Pressing a key is probably the way to go, especially if you are already at the terminal with fingers on the keys.

chrome://inspect appears to get notified when a connection comes online. I wonder if there are callbacks for monitoring ports?   I looked into the package Portastic for some clues but it seems to poll for an open connection every 100ms.

**Comment by jkrems** [comment]
`chrome://inspect` is also polling the `/json` endpoint. But maybe its frequency is less than 3 seconds? To clarify: it wouldn't be a technical problem to poll and automatically reconnect. But since connecting can force a break event that seems a bit annoying. I could foresee someone using `nodemon` etc. and being annoyed that the debugger keeps forcing a break on every single file save.

**Comment by lukerohde** [comment]
Good point.  I'm a node newbie.  An auto-reconnect flag?

**Comment by Trott** [comment]
This has been dormant for over 4 years so I'm going to close it. However if it is still a desirable feature, open an issue in https://github.com/nodejs/node as that's where node-inspect now lives. This repository will be archived at some point in the not-too-distant future.
