### ISSUE TITLE
Add regression tests for autocomplete

### ISSUE THREAD

**Issue by jkrems** [nodejs/node-inspect#29]
*Follow-up to https://github.com/nodejs/node-inspect/pull/28.*

Right now we have no tests that check for `<tab>`-completion. We should add some for both command- & repl mode.

**Comment by aqrln** [comment]
@jkrems if you're not already working on this, I'd like to take a peek at that. Can I find you on IRC or somewhere if I have any questions?

**Comment by jkrems** [comment]
That'd be great! I'm rarely on IRC (can't figure out a productive way of using it) but I'd be happy to answer any questions here or [on Twitter](https://twitter.com/jankrems/).

**Comment by aqrln** [comment]
Okay :)

**Comment by aqrln** [comment]
@jkrems sorry for the delay, I have not forgotten this, just was a lot more busy that I hoped for. Will start working on it tonight.

**Comment by jkrems** [comment]
No worries, I know the feeling... :D

**Comment by Trott** [comment]
This has been dormant for over 4 years so I'm going to close it. However if it is still a desirable feature, open an issue in https://github.com/nodejs/node as that's where node-inspect now lives. This repository will be archived at some point in the not-too-distant future.
