### ISSUE TITLE
exceptions.test.js breakpoint on AIX different

### ISSUE THREAD

**Issue by CurryKitten** [nodejs/node-inspect#33]
Looking at the problems testing on aix (Issue #24) I discovered a strange problem when running the exceptions.test.js test.

The test runs the debugger using the code in examples/exceptions.js and expects an initial breakpoint of line 1.  But on AIX, this breakpoint hits at line 2.  This is easily recreated on the command line -

```
$ node cli examples/exceptions.js
< Debugger listening on port 9229.
< Warning: This is an experimental feature and could change at any time.
< To start debugging, open the following URL in Chrome:
<     chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/f0eb458e-25a2-44cd-8a73-d74ecc4f60eb
< Debugger attached.
break in examples/exceptions.js:2
  1 (function (exports, require, module, __filename, __dirname) { 'use strict';
> 2 let error = null;
  3 try {
  4   throw new Error('Caught');
debug> 
```
Running the same command on a Linux machine will break on line 1 as expected.  I tried this on my own OSX machine (Sierra) and this hit line 2, although I note that the ci tests pass on OSX here, so would like to check if there's any particular version changes that differentiate the two.  Would assume this could be an issue in v8

**Comment by jkrems** [comment]
Weird, just tried on Sierra as well (node 6/7/8) and it always stopped at line 1. I'd say it would be perfectly fine to make the test suite accept either line 1 or 2, given that the first line is a "useless" noop that doesn't really get executed/stepped over.

**Comment by jkrems** [comment]
I think this was fixed by pulling in https://github.com/nodejs/node-inspect/pull/34.
