### ISSUE TITLE
AIX: Breakpoint resolved isn't handled properly on restart

### ISSUE THREAD

**Issue by jkrems** [nodejs/node-inspect#35]
*See TODO in `test/cli/preserve-breaks.test.js`.*

Expected output of `breakpoints` after restart:

```
#0 examples/three-lines.js:2
#0 examples/three-lines.js:3
```

Actual output (still showing the regex for matching the filename that should've been resolved):

```
#0 .*//path/to/node-inspect/examples/three-lines.js$:2
#1 .*//path/to/node-inspect/examples/three-lines.js$:3
```

These "fake filenames" are generated when setting a breakpoint in a file that has been loaded yet:

```js
// inspect_repl.js
        if (!bp.location) { // Fake it for now.
          Object.assign(bp, {
            actualLocation: {
              scriptUrl: `.*/${script}$`,
              lineNumber: line - 1,
            },
          });
```

**Comment by gibfahn** [comment]
cc/ @currykitten

**Comment by mhdawson** [comment]
@currykitten can you take a look at this so we can discussion when we talk on Friday ?

**Comment by CurryKitten** [comment]
@mhdawson Ok - I'm looking into it

**Comment by CurryKitten** [comment]
I'm finding that I can no longer recreate this issue.  I could previous recreate is very easily just by running node-inspect against `test/three-lines.js`, setting multiple breakpoints and then restarting a few times.

I've been running it through several hundred iterations, can't recreate the failure.  We still have the warning that the file hasn't been loaded yet (as well as on other platforms) but the regex in the path is properly resolved.  Did the delay added in #34 also fix this ?

**Comment by jkrems** [comment]
Maybe..? Should we remove the AIX special case in the test and see how it goes?

**Comment by Trott** [comment]
Optimistically closing based on https://github.com/nodejs/node/pull/39238

**Comment by Trott** [comment]
Hmmm....although I guess it should stay open until https://github.com/nodejs/node/blob/1544e69b93565c97e7ed232bf2db237d34b8fd7c/test/common/debugger.js#L26-L29 is resolved/removed.

**Comment by Trott** [comment]
Workaround code has been removed so this at least appears to be fixed.
