### ISSUE TITLE
Freeze UUID token in chrome devtools link

### ISSUE THREAD

**Issue by darky** [nodejs/node-inspect#45]
During developing process very uncomfortable open chrome devtools again and again by new generated link. I want to pass like: `--inspect-token=00000000-0000-0000-0000-000000000000` or better: `--inspect-token=developing` and already have the same link, that allow me simple refresh browser tab, when node process will restarted

**Comment by ofrobots** [comment]
Chrome 57+ comes with a dedicated DevTools for Node.js that gets rid of the need to copy/paste the URL across restarts:

![image](https://cloud.githubusercontent.com/assets/79017/25235001/b6032d86-2598-11e7-98f0-b54b5e6e8591.png)

Can you give this a shot and see if this addresses your use-case?

**Comment by darky** [comment]
@ofrobots, it not resolved this problem. When node.js process restarted, need to click again on *inspect* link and open new window with actual process. Old window not working after restart.

**Comment by ofrobots** [comment]
For me it does seem to work after a restart. @eugeneo: does this behaviour make sense to you?

**Comment by darky** [comment]
@ofrobots, I don't understand how it works for you, it not logical due to this behaviour

> When node.js process restarted, need to click again on inspect link and open new window with actual process. Old window not working after restart.

Also, I think, that this token need for security reasons, but, if `chrome://inspect` can simply find attached process, why it need?..

**Comment by jkrems** [comment]
@darky To clarify: There's two links. @ofrobots was talking about this one if I understand him correctly:

<img width="551" alt="screen shot 2017-04-20 at 8 31 09 am" src="https://cloud.githubusercontent.com/assets/567540/25239042/d26e75c4-25a3-11e7-8544-7d71c47fa037.png">

If you're using the default port for `--inspect`, that link should work and keep working without any re-opening of the DevTools.

**Comment by jkrems** [comment]
I'm afraid this issue isn't actually about `node-inspect` (the command line debugger) but about the v8 inspector integration itself (`node --inspect`). There are already issues in `nodejs/node`:

* Node --inspect uuid - https://github.com/nodejs/node/issues/11701
* programmatically expose the V8 inspector URL - https://github.com/nodejs/node/issues/11496

Feel free to open a new issue in [`nodejs/node`](https://github.com/nodejs/node/issues) for this feature request! :)

**Comment by darky** [comment]
@jkrems, thanks for the answer
