### ISSUE TITLE
Network request inspection

### ISSUE THREAD

**Issue by talawahtech** [nodejs/node-inspect#52]
Hi,

Any plans to add support for inspecting network requests?

**Comment by jkrems** [comment]
Yes, absolutely. The problem is that right now the instrumentation required for this feature doesn't exist in node itself. There's an issue tracking the work on the required APIs: https://github.com/nodejs/diagnostics/issues/75

**Comment by hybrist** [comment]
The diagnostics issue was closed (because it realistically won't happen without investment from the devtools side). The best place to watch may be https://github.com/GoogleChromeLabs/ndb/pull/282 at this point.
