### ISSUE TITLE
Timeout (2000) waiting for 127.0.0.1:9229 to be free

### ISSUE THREAD

**Issue by Michelle0609** [nodejs/node-inspect#54]
Hi ,I got the following issue while executing the debug command from cmd

There was an internal error in node-inspect. Please report this bug.
Timeout (2000) waiting for 127.0.0.1:9229 to be free

Error: Timeout (2000) waiting for 127.0.0.1:9229 to be free
    at Timeout.setTimeout [as _onTimeout] (node-inspect/lib/_inspect.js:63:14)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)

The script is very simple:
var person={
name:'Michelle'
};
person.age=25;
person.name='Mike';
console.log(person);

Command: node inspect app.js

**Comment by JorgeTheCreator** [comment]
There could be the slightest possibility, that you are running "node inspect" on two terminal window. Make sure you close ALL your terminal windows and run the test on one.

**Comment by anton-st** [comment]
Same problem running nodejs docker example app (https://nodejs.org/en/docs/guides/nodejs-docker-webapp/). Connected terminal to the container and run:

kill -s USR1 <PID>
curl localhost:9229/json/list  - works fine, returns "webSocketDebuggerUrl"
node inspect 127.0.0.1:9229/<ID> - returns error below.

There is only one instance of node inspect.
Error:
There was an internal error in node-inspect. Please report this bug.
Timeout (2000) waiting for 127.0.0.1:9229 to be free
Error: Timeout (2000) waiting for 127.0.0.1:9229 to be free
    at Timeout.setTimeout [as _onTimeout] (node-inspect/lib/_inspect.js:63:14)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

**Comment by 4rch1m3d35** [comment]
i am having this same issue and i only have one terminal window that is attempting to run node inspect at one time i opened this thread in the help section
https://github.com/nodejs/help/issues/1909

**Comment by linqOxelar** [comment]
same issue here and i have checked Windows' used ip:port and no entry is using port 9229

**Comment by yilmazdurmaz** [comment]
please check : https://github.com/nodejs/node-inspect/issues/48#issuecomment-520246415

**Comment by Manish-Kumarr** [comment]
if you will using node --inspect-brk instead of node inspect. It will be work.

**Comment by PrasathRavichandran** [comment]
> Unfortunately the code of the bundled version is part of the node binary (`node.exe`). It's not stored separately on disk. You could also try the following:
> 
> 1. Run `node --inspect-brk your-script.js`.
> 2. Run `node inspect localhost:9229` in a separate terminal tab/window.
> 
> Restarting the target is now a bit more annoying (it requires both restarting the actual script being debugged and then using the `restart` (or `r`) command in the `node inspect` repl to reconnect. But it may be easier as a workaround.

**Comment by aleleonian** [comment]
> > Unfortunately the code of the bundled version is part of the node binary (`node.exe`). It's not stored separately on disk. You could also try the following:
> > 
> > 1. Run `node --inspect-brk your-script.js`.
> > 2. Run `node inspect localhost:9229` in a separate terminal tab/window.
> > 
> > Restarting the target is now a bit more annoying (it requires both restarting the actual script being debugged and then using the `restart` (or `r`) command in the `node inspect` repl to reconnect. But it may be easier as a workaround.

👌 
This works for me.
