### ISSUE TITLE
Internal error in node-inspect. Please report this bug. 

### ISSUE THREAD

**Issue by LEQADA** [nodejs/node-inspect#60]
### Description 

When the port is busy – node-inspect throws a timeout exception which is logged as an internal error.

- **Version:** v9.7.1
- **Platform:** Windows 10 x64
- **Subsystem:** node-inspect

```
node debug .
(node:14108) [DEP0068] DeprecationWarning: `node debug` is deprecated. Please use `node inspect` instead.
There was an internal error in node-inspect. Please report this bug.
Timeout (2000) waiting for 127.0.0.1:9229 to be free
Error: Timeout (2000) waiting for 127.0.0.1:9229 to be free
    at Timeout.setTimeout [as _onTimeout] (node-inspect/lib/_inspect.js:54:14)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
```

### Overview

Timeout message is generated here
https://github.com/nodejs/node-inspect/blob/3c9073f8a55e7b1a34bc47e5c5ddaaa942967fd3/lib/_inspect.js#L52-L56

and then catched by a handler 

https://github.com/nodejs/node-inspect/blob/3c9073f8a55e7b1a34bc47e5c5ddaaa942967fd3/lib/_inspect.js#L348-L355

**Comment by jkrems** [comment]
Suggestion by @bnoordhuis:

> Would logging a message followed by process.exit(1) in the timer callback work?

Suggestion by @jkrems:

> Alternatively: making it a non-fatal error. "Failed to start app. Please check that the port isn't used by anything else. Use run to try again." etc.. Another solution would be to use a custom code and/or error class (StartupError) and exclude that from the internal error message. But that seems a bit more hacky.

**Comment by LEQADA** [comment]
@bnoordhuis I think it will work. But I'm not sure is it good to `process.exit(1)` in 2 places 🤔 
@jkrems I'm not quite sure what you mean by making it non-fatal error. To not reject? Create another type of handler? Could you give me an example?

**Comment by jkrems** [comment]
By "non-fatal error" I meant starting the repl instead of exiting the `node-inspect` process. Then the user just needs to type `restart` to retry if they fixed the other process. That might also address cases where the app crashed, the user is trying to run it again (`run<enter>`), and they run into the same problem (another process is blocking the port).

**Comment by jkrems** [comment]
But I'd be more than happy to merge a simpler solution that just hides away the "internal error" message *somehow*. There's always time to improve the UX even further in the future.

**Comment by jkrems** [comment]
Potential fix is here: https://github.com/nodejs/node-inspect/pull/62
