### ISSUE TITLE
Can I delete or disable the node-inspect-continuous-integration ci job?

### ISSUE THREAD

**Issue by sam-github** [nodejs/node-inspect#69]
job: https://ci.nodejs.org/job/node-inspect-continuous-integration

It appears to be unused. It lacks configuration for any node versions after 8.x, for example.

I also kicked off a build, and it instantly failed on all its current platforms: https://ci.nodejs.org/job/node-inspect-continuous-integration/49/

**Comment by jkrems** [comment]
Yeah, feel free to delete it. At some point I had planned to look into setting up a working build or fixing the existing one. But realistically that's not happening anytime soon.

**Comment by sam-github** [comment]
Thanks @jkrems , it is gone. And of course, should you want to take another shot sometime you are welcome to.
