### ISSUE TITLE
Same problem : Timeout (2000) waiting for 127.0.0.1:9229 to be free

### ISSUE THREAD

**Issue by linqOxelar** [nodejs/node-inspect#70]
Same problem : Timeout (2000) waiting for 127.0.0.1:9229 to be free

Windows x64 18362.207
Node 12.6.0

and i have checked used ip:port (netstat command) and no entry is using this port

_Originally posted by @linqOxelar in https://github.com/nodejs/node-inspect/issues/48#issuecomment-509000471_

**Comment by yilmazdurmaz** [comment]
please check: https://github.com/nodejs/node-inspect/issues/48#issuecomment-520246415
