### ISSUE TITLE
Document how to inject a certain script of commands into the command line debugger to be executed one by one similar to gdb's --command flag

### ISSUE THREAD

**Issue by shlomif** [nodejs/node-inspect#74]
Hi!

Please document how to inject a certain script of commands into the command line debugger to be executed one by one similar to gdb's `--command` flag.

See:

https://stackoverflow.com/questions/59291241/how-can-i-script-automate-node-jss-node-inspector-debugger-by-giving-a-sequen

No one on freenode's ##javascript or ##node.js could enlighten me on that and I was referred to https://nodejs.org/api/inspector.html but there isnt an example like that there. So I'm filing an issue for lacking documentation/example code.

**Comment by jkrems** [comment]
I think the short answer is that reliable scripting, especially on startup, isn't really supported right now. If you're willing to write a bit of JS, you could copy what the `node-inspect` test suite does. You can find an example here: https://github.com/nodejs/node-inspect/blob/af55a32c0f91c7e7214ad816313c6ea4ed2e50e2/test/cli/exec.test.js#L14-L16

It should be possible to implement proper support for this but it would take some work. I'd be happy to assist / guide you through it if you want to give it a shot!

**Comment by shlomif** [comment]
On Tue, 17 Dec 2019 08:03:27 -0800
Jan Olaf Krems <notifications@github.com> wrote:

> I think the short answer is that reliable scripting, especially on startup,
> isn't really supported right now. If you're willing to write a bit of JS, you
> could copy what the `node-inspect` test suite does. You can find an example
> here:
> https://github.com/nodejs/node-inspect/blob/af55a32c0f91c7e7214ad816313c6ea4ed2e50e2/test/cli/exec.test.js#L14-L16
> 
> It should be possible to implement proper support for this but it would take
> some work. I'd be happy to assist / guide you through it if you want to give
> it a shot!
> 

Thanks! I'm willing to write some JS. I'll try your suggestion and let you know.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/bits/facts/Summer-Glau/

Knuth is not God! Unless you confuse him with Dijkstra.
    — http://www.shlomifish.org/humour/bits/facts/Knuth/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Hi all and happy holidays! Sorry if I am being too needy but why does this program - https://github.com/shlomif/fc-solve/blob/89110ad906bf608a5a8290c46ddac425bae0fced/fc-solve/site/wml/bin/node_inspect_debugger_exec.js - gives me this error:

```
++ pwd
+ export NODE_PATH=/home/shlomif/progs/freecell/git/fc-solve/fc-solve/site/wml/lib/for-node/js
+ NODE_PATH=/home/shlomif/progs/freecell/git/fc-solve/fc-solve/site/wml/lib/for-node/js
+ node bin/node_inspect_debugger_exec.js
TAP version 13
# Subtest: startCLI
    1..0
ok 1 - startCLI # time=2.129ms

sparkle

< Debugger listening on ws://127.0.0.1:9229/92532de5-cf89-41d1-833e-e92b8c16ec4f
< For help, see: https://nodejs.org/en/docs/inspector
connecting to 127.0.0.1:9229 ... okdebug> < Debugger attached.
Break on start in node_modules/qunit/bin/qunit.js:5
  3 "use strict";
  4 
> 5 const program = require( "commander" );
  6 const run = require( "../src/cli/run" );
  7 const FindReporter = require( "../src/cli/find-reporter" );
debug> 
apploo idx=0;

vwooby idx=1 cmd=sb(7);

cli.command returned error at idx=1; error=<<<Error: Child quit while waiting for />\s+$/; found: undefined>>>

1..1
# time=136.851ms

```

what am I doing wrong?

**Comment by shlomif** [comment]
Hi all!

An update: after experimenting with several approaches, I ended up debugging using `console.log` and was able to write an ugly fix/workaround: https://github.com/shlomif/fc-solve/blob/8c33a1afc820821f4cbb09388fc72d4a8a641151/fc-solve/site/wml/bin/qunit-for-fc-solve-site#L19-L25 . You can find some attempts at automating node inspector here: https://github.com/shlomif/fc-solve/tree/emcc-tests-investigation--take3-api .

I do wish the reported issue to be made easier for future needs. From what I recall I was unable to print the entire output as in the manually controlled debugger.

**Comment by hybrist** [comment]
The stable protocol for automating debugging already exists and it's the Chrome DevTools protocol. Making it easier to automate a CLI client on top of that already existing protocol seems backwards.

If you'd like to reopen this issue, it would likely be best to open it directly in [nodejs/node](https://github.com/nodejs/node) since we're planning to archive this repo.
