### ISSUE TITLE
.travis.yml references an EOL node version

### ISSUE THREAD

**Issue by dominykas** [nodejs/node-inspect#88]
I was going through `.travis.yml` across the org to look for outdated Node.js versions and spotted this repo referencing `6.8`. Does it need a bump?

Not sure what this is used for - is it meant to be testing in a single version? If so - might make sense to just change the version to `lts/*` or `latest`? If it's meant to test in multiple versions - it may be worth using one of the shared configs at https://github.com/nodejs/ci-config-travis to automatically include new versions?

Happy to PR, if needed.

**Comment by dominykas** [comment]
Also not sure what's the status of #21...

**Comment by jkrems** [comment]
Thanks for bringing this up! I think the travis config could be deleted at this point, the repo was switched to Github workflows a while back.
