### ISSUE TITLE
Problem with profiling in-client commands not returning anything

### ISSUE THREAD

**Issue by daminebenq** [nodejs/node-inspect#94]
**--** `index.js` **--**
```
setInterval(()=> {
   console.log('Hi');
}, 1000);
```

**--** `inspect.js` **--** (`start-cli.js` used in this file is the same as [start-cli.js](https://github.com/nodejs/node-inspect/blob/master/test/cli/start-cli.js))
```
const startCLI = require('./start-cli'); // start-cli.js used in node-inspect examples
const path = require('path');

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

const randomNmbr = () => parseInt(Date.now() * Math.random());
const file = path.join(__dirname, 'profile-'+randomNmbr()); // file to save profile

const cli = startCLI(['127.0.0.1:9229']); // pointing the client to host:port

  function onFatal(error) {
    cli.quit();
    throw error;
  }

  return cli.command('profile')
    .then(() => console.log('profiling....'))
    .then(() => delay(5000))
    .then(() => {
      let  commandReturn = cli.command('profileEnd')
      console.log("Returned ended profile: ", commandReturn)
    }) 
    .then(() =>   { // not showing generated profiles
      let  commandReturn = cli.command('profiles');
      console.log("returned profiles: ", commandReturn)
    }) 
    .then(() => console.log('profiling ended.'))
    .then(() => {
      let commandReturn = cli.command(`profiles[0].save('${file}')`);
      console.log("return: ", commandReturn);
    })
    .then(() => console.log('output file: ', file))
    .then(() => cli.quit())
    .then(null, onFatal);
```

**In my scripts, I'm doing the following:**
1) running `node index.js`
2) kill it using `kill -USR1 <pid>` from a second terminal
3) running `node inspect.js`

and I get the following:
![image](https://user-images.githubusercontent.com/5144311/99007400-e40b6580-2522-11eb-8a67-2ec2634e7e06.png)

**Expected results:**
1) a new file should be generated and saved in the execution folder
2) there should be a return after executing `profileEnd` showing for example: `[Profile 2915697μs]` 
3) there should be `profiles` returned
4) there should be a return like: `Saved profile to /home/user/path-to-folder/node-inspect/fileName`

any help ?

**Comment by hybrist** [comment]
These functions aren't really meant to be a public API and since we moved the code to node itself, they aren't accessible from the outside anymore. If the goal is automation, it'll likely be more stable to build on top of something like `devtools-client`.
